//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalAsignment.Data
{
    using System;
    
    public enum StatusType : byte
    {
        Success = 0,
        Failed = 1,
        Canceled = 2
    }
}
